### ISSUE TITLE
AUB checklist

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss-deprecated/dlme-metadata#30]
- [x] find contact
- [x] send request
- [x] permission granted
- [ ] harvest (al-adab, postcards)
- [ ] map & stage (al-adab, postcards)
- [ ] review (al-adab)
- [ ] production (al-adab)

Notes:
Permission granted to harvest the four collections that have been migrated to the new site. Awaiting clarification about the yearbooks collection. AUB is in the process of building a new API and the urls will change. The first set al-adab has been harvested, mapped, and loaded in stage. An email has been sent with guidelines for review. Awaiting feedback on mapping and information on other collections (7/1/2019). 

Collections of interest (permission granted):
http://digitalcollections.aucegypt.edu/cdm/landingpage/collection/p15795coll9
http://ddc.aub.edu.lb/projects/jafet/artposters/index.html
http://ddc.aub.edu.lb/projects/jafet/blatchford/
http://ddc.aub.edu.lb/projects/jafet/manuscripts/
http://ddc.aub.edu.lb/projects/jafet/moore/index.html
http://ddc.aub.edu.lb/projects/jafet/posters/english.html
https://libraries.aub.edu.lb/digital-collections/collection/postcards
https://libraries.aub.edu.lb/xtf/search?browse-all=yes;brand=travelbooks;collection=travelbooks
https://libraries.aub.edu.lb/poha/ 
http://al-adab.com/archive

Collections of interest (need permission):
http://192.168.100.128:9494/digital-collections/collection/campus
