### ISSUE TITLE
BnF & IFAO checklist 

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss-deprecated/dlme-metadata#35]
- [x] find contact
- [x] send request: 4/23/2019 Macquin
- [x] permission granted: Gallica collection granted, others "not harvestable"
- [ ] harvest: harvesting possible, sent renewed request 8/27/2019, forwarded to relevant parties 9/19/2019
- [ ] map & stage
- [ ] review
- [ ] production

Notes:
The Gallica collection has an open source license. We have harvested this collection but we still want to get in touch with IFAO to build a relationship and to seek permission for the other two collections. Elizabeth contacted Ms. Macquin (bibliotheque@ifao.egnet.net) on 4/10/2019. Ms. Macquin replied on 4/23/19 that IFAO in principle supports their Gallica collection being in the DLME but her understanding is the BnF owns the metadata, so she cc'd folks at the BnF on her response. She also indicated their other online collections are not "harvestable." Elizabeth replied  April 29 that the DLME has permission from BnF to harvest Gallica data as long as the stewarding institution is in favor, so we will proceed with federating the IFAO records in Gallica into the DLME. Elizabeth also asked whether the IFAO knows of collection-level records for the 2 unharvestable collections (Bruyere archives and Tombes de Deir el-Medineh). Out of office message indicated Agnes is out through May 4.

Collections of interest:
http://www.ifao.egnet.net/bases/archives/bruyere/
http://www.ifao.egnet.net/bases/archives/ttdem/
https://gallica.bnf.fr/services/engine/search/sru?operation=searchRetrieve&version=1.2&startRecord=0&maximumRecords=50&page=1&collapsing=true&exactSearch=false&query=dc.source%20all%20%22Institut%20fran%C3%A7ais%20d%E2%80%99arch%C3%A9ologie%20orientale%22%20%20and%20%28provenance%20adj%20%22bnf.fr%22%29
