### ISSUE TITLE
BnF EBAF checklist

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss-deprecated/dlme-metadata#37]
To Do:
- [x] Locate contacts for EBAF & send request
- [ ] Contact Jean-Michel de Tarragon in April 2020
- [ ] Obtain permission to harvest
- [x] Harvest records

Harvested records and they are open source but need to contact EBAF to establish relationship. Jacob contacted Fr. Jean-Michel de Tarragon (tarragon@ebaf.edu) and Fr. Martin Staszak (mnstaszak@gmail.com) on 4/19/2019. Jean-Michel de Tarragon replied on 4/25/2019 that such a collaboration would be too soon for them. They have 30,000 images in total and they wish to build their own website first. Suggested that we could revisit the issue in a year.

Collections of interest:
https://gallica.bnf.fr/services/engine/search/sru?operation=searchRetrieve&version=1.2&startRecord=0&maximumRecords=50&page=1&collapsing=true&exactSearch=false&query=dc.source%20all%20%22%20Ecole%20biblique%20et%20arch%C3%A9ologique%20fran%C3%A7aise%20de%20J%C3%A9rusalem%22%20%20and%20%28provenance%20adj%20%22bnf.fr%22%29

**Comment by jacobthill** [comment]
Received a message from Fr. Jean-Michel de Tarragon on 4/24/2019 stating that EBAF was not in a position to collaborate at this time but that we should check back in one year to explore the possibility of partnering with the DLME at that time.
