### ISSUE TITLE
W.F. Albright Institute checklist

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss-deprecated/dlme-metadata#63]
Curatorial:
- [x] Locate contacts for EBAF & send request
- [x] Obtain permission to harvest
- [x] Harvest records

Collections of interest:
http://www.aiar.org/library/map-collection/

Elizabeth emailed Albright director Matt Adams April 30. He replied May 7 they are happy to participate and cc'd their systems librarian Diana Steigler. @jacobthill is working on determining the best method of harvesting the metadata. Seems like a small collection without a dedicated API. The records are stored as rows in an html table. Diana shared the data (Marc xml) via email.

Mapping:
- [x] Complete initial draft
- [ ] Add urls (not provided in metadata)
- [ ] Add a way of generating thumbnails from images (not provided in metadata)
- [ ] Add language fields (not provided in metadata)
