### ISSUE TITLE
QNL checklist

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss-deprecated/dlme-metadata#67]
- [ ] Re-harvest data once revision is complete (waiting on Cogapp to make changes)
- [ ] Add thumbnails
- [ ] Add role of contributor/creator 
- [ ] Check revised edm-type
