### ISSUE TITLE
AUC checklist

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss-deprecated/dlme-metadata#68]
- [x] find contact
- [x] send request for [new collection](http://digitalcollections.aucegypt.edu/cdm/landingpage/collection/p15795coll7) sent 1/14/20
- [ ] send date errors
- [ ] permission
- [ ] harvest
- [ ] map & stage: blocked by https://github.com/sul-dlss/dlme/issues/527
- [ ] review
- [ ] production

Cleanup to do:
- [x] Delete old data (collection 33 has 3 items in it; the collection has been deleted from dlme-metadata but it is still in the staging environment)
- [ ] Reload data in stage and confirm that it works as expected
