### ISSUE TITLE
Harvard checklist

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss-deprecated/dlme-metadata#69]
- [x] find contact
- [x] send request: S. Wones 6/4/2019
- [x] permission: granted 6/4/2019
- [x] harvest
- [ ] get permission for [new collection](https://curiosity.lib.harvard.edu/iranian-oral-history-project/catalog?search_field=all_fields)
- [ ] fix thumbnails for Harvard maps (not consistently working)
- [ ] review: 
- [ ] production

Collections of interest:
