### ISSUE TITLE
Cambridge checklist

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss-deprecated/dlme-metadata#76]
- [x] find contact
- [x] send request: Mr. Jones and Mr Corrigan on 7/11/2019
- [x] permission: granted for first 3 collections, await last 2
- [x] harvest
- [x] map & stage
- [ ] review: sent request 8/27/2019
- [ ] production

Collections of interest: 
https://cudl.lib.cam.ac.uk/iiif/collection/islamic
https://cudl.lib.cam.ac.uk/iiif/collection/hebrew
https://cudl.lib.cam.ac.uk/iiif/collection/genizah
https://cudl.lib.cam.ac.uk/iiif/collection/ras
https://cudl.lib.cam.ac.uk/iiif/collection/aiit
