### ISSUE TITLE
Bodleian checklist

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss-deprecated/dlme-metadata#86]
- [x] find contact
- [x] send request: Mr. Popham, Mr. Bonnie 8/29/2019
- [x] permission granted: Mr. Popham 8/30/2019
- [x] harvest
- [ ] permission for [new collection](https://genizah.bodleian.ox.ac.uk)
- [ ] map & stage
- [ ] review
- [ ] production

Collections of interest:
- Hebrew, including Judaeo-Arabic: https://iiif.bodleian.ox.ac.uk/iiif/collection/hebrew
- Armenian: https://iiif.bodleian.ox.ac.uk/iiif/collection/armenian
- Arabic: https://iiif.bodleian.ox.ac.uk/iiif/collection/arabic
