### ISSUE TITLE
Leiden checklist

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss-deprecated/dlme-metadata#89]
- [x] find contact
- [x] send request: Mr. Vat & van der Plas 9/2/2019
- [x] permission granted: Marco de Niet 9/11/2019
- [ ] harvest: ready to harvest early 2020
- [ ] map & stage
- [ ] review
- [ ] production

Collections of interest:
https://digitalcollections.universiteitleiden.nl/search?type=dismax&islandora_solr_search_navigation=1&f%5B0%5D=RELS_EXT_isMemberOfCollection_uri_ms%3A%22info%5C%3Afedora%5C/collection%5C%3Aubl_manuscripts%22&f%5B1%5D=mods_language_languageTerm_text_authority_iso639%5C-2b_ms%3A%22Arabic%22
https://digitalcollections.universiteitleiden.nl/search?type=dismax&islandora_solr_search_navigation=1&f%5B0%5D=RELS_EXT_isMemberOfCollection_uri_ms%3A%22info%5C%3Afedora%5C/collection%5C%3Aubl_manuscripts%22&f%5B1%5D=mods_language_languageTerm_text_authority_iso639%5C-2b_ms%3A%22Arabic%22&f%5B2%5D=mods_language_languageTerm_text_authority_iso639%5C-2b_ms%3A%22Persian%22
